---
deployment:
  tasks:
    - export DEPLOYPATH=/home4/jeissonr/public_html
    - /bin/cp index.html $DEPLOYPATH/
    - /bin/cp -r css/ $DEPLOYPATH/css/
    - /bin/cp -r js/ $DEPLOYPATH/js/
    - /bin/cp -r pictures/ $DEPLOYPATH/pictures/
